name: 'Auto Assign'
on: pull_request

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          key: d4624ac374daa2faa4f5079b18a1911cfa05c515
          configuration-path: ".github/workflows/auto_assign.yml"
          addReviewers: true
          addAssignees: false
          reviewers: obi-wan-shinobi
